In [4]:
import pandas as pd

In [16]:
data = pd.read_csv('../data/wmt15.en-cs.csv', sep='\0', header=None, names=['en'])
data['en'] = data['en'].str.replace(r"[^\w '\.,\-]", "", regex=True)
data = data[data['en_len'] >= 10]

In [50]:
data['en_len']  = data['en'].str.len()
data[data['en_len'] > 2].head()
data = data.sort_values(by='en_len')
data['cumsum'] = data['en_len'].cumsum()

In [51]:
selected_data = data[data['cumsum'] < 2_000_000]

In [54]:
selected_data.head(20)

                 en  en_len  cumsum
8465850  Williamson      10      10
3279924  Mic Volume      10      20
4184781  What tank       10      30
242852   Nay , nay       10      40
2873390  190 Width       10      50
1663669  Port State      10      60
3584943  Finetuning      10      70
3122345  For Miles       10      80
1663660  Key ratios      10      90
1992497  Sold out .      10     100
6527440  Dry matter      10     110
4867263  Zorro Hat       10     120
3582008  'Warning .      10     130
4720449  INITIATIVE      10     140
8728558  'Bursar  '      10     150
1667167  Sort Items      10     160
887227   That soon       10     170
3121820   Powerful       10     180
9288095  Off we go       10     190
4316259  Time  Date      10     200